billing_masterData = [{"prodid":"1",
    "prodName":"Apple",
    "ProdCategory":"Fruits and veggies",
    "unitPrice":2},
  {"prodid":"2",
    "prodName":"Orange",
    "ProdCategory":"Fruits and veggies",
    "unitPrice":3},
    {"prodid":"3",
    "prodName":"Banana",
    "ProdCategory":"Fruits and veggies",
    "unitPrice":1},
    {"prodid":"4",
    "prodName":"Onion",
    "ProdCategory":"Fruits and veggies",
    "unitPrice":2},
    {"prodid":"5",
    "prodName":"Peppers",
    "ProdCategory":"Fruits and veggies",
    "unitPrice":1},
    {"prodid":"6",
    "prodName":"Chicken",
    "ProdCategory":"Poultry",
    "unitPrice":4},
    {"prodid":"7",
    "prodName":"Egg",
    "ProdCategory":"Poultry",
    "unitPrice":5},
    {"prodid":"8",
    "prodName":"Fish",
    "ProdCategory":"Poultry",
    "unitPrice":10},
    {"prodid":"9",
    "prodName":"Dish Soap",
    "ProdCategory":"Kitchen Supplies",
    "unitPrice":2},
    {"prodid":"10",
    "prodName":"Hand Sanitizer",
    "ProdCategory":"Bath and Body Supplies",
    "unitPrice":3},
    {"prodid":"11",
    "prodName":"Perfume",
    "ProdCategory":"Bath and Body Supplies",
    "unitPrice":10},
    {"prodid":"12",
    "prodName":"Shampoo",
    "ProdCategory":"Bath and Body Supplies",
    "unitPrice":6},
    {"prodid":"13",
    "prodName":"Conditioner",
    "ProdCategory":"Bath and Body Supplies",
    "unitPrice":7},
    {"prodid":"14",
    "prodName":"Body lotion",
    "ProdCategory":"Bath and Body Supplies",
    "unitPrice":10},
    {"prodid":"15",
    "prodName":"Ketchup",
    "ProdCategory":"Groceries",
    "unitPrice":5},
    {"prodid":"16",
    "prodName":"Pasta Sauce",
    "ProdCategory":"Groceries",
    "unitPrice":5},
    {"prodid":"17",
    "prodName":"Salsa",
    "ProdCategory":"Groceries",
    "unitPrice":6},
    {"prodid":"18",
    "prodName":"Potato Chips",
    "ProdCategory":"Snacks",
    "unitPrice":3},
    {"prodid":"19",
    "prodName":"Almonds",
    "ProdCategory":"Snacks",
    "unitPrice":20},
    {"prodid":"20",
    "prodName":"Cashews",
    "ProdCategory":"Groceries",
    "unitPrice":22},
    {"prodid":"21",
    "prodName":"Mop",
    "ProdCategory":"Cleaning Supplies",
    "unitPrice":30},
    {"prodid":"22",
    "prodName":"Broom",
    "ProdCategory":"Cleaning Supplies",
    "unitPrice":12},
    {"prodid":"23",
    "prodName":"All purpose Spray",
    "ProdCategory":"Cleaning Supplies",
    "unitPrice":4},
    {"prodid":"24",
    "prodName":"Salad",
    "ProdCategory":"Food",
    "unitPrice":5},
    {"prodid":"25",
    "prodName":"Ice Cream",
    "ProdCategory":"Frozen",
    "unitPrice":12}]